### ISSUE TITLE
funny.

### ISSUE THREAD

**Issue by dropout1337** [Aran404/Nitro-Redeemer#4]
"Imagine a 14 year old kid can bypass a 95 billion dollar company (Stripe) in full requests."
You aren't bypassing anything dear buddy, before you use the term bypass why don't you figure out the meaning.
All you did was automate (aka copy requests) not a hard thing to do in any way. Any developer who has a head can copy requests and create said tool.

**Comment by Aran404** [comment]
Fair enough but there was much more that went into it than just mimicking the request fully.

**Comment by Aran404** [comment]
Also please check out what stripe uses before you start talking, stripe uses 3D Secure 2 which isn't a matter of copying every curl and converting them to your desired language but also involves steps to stop your vcc from getting flagged or stripes server from flagging a payment as suspicious.

**Comment by dropout1337** [comment]
I have worked with stripes undocumented api before, if you can use your head it becomes quite easy.

**Comment by dropout1337** [comment]
Aran, I'm sorry about this issue. I was very high and sleep deprived at the time. I hope this doesn't bring any bad water between us :)
